## Geometry Analysis Project

In [65]:
import numpy
import os

In [66]:
file_location= os.path.join('water.xyz')
print(file_location)

water.xyz


In [67]:
#def function_name(parameters):
#***code goes***
# return value_to_return

In [68]:
def calculate_distance(coords1, coords2):
    """"
    This function has two arguments, the coordinates of two atoms. It returns the distance between two atoms.
    """
    x_distance=coords1[0]-coords2[0]
    y_distance=coords1[1]-coords2[1]
    z_distance=coords1[2]-coords2[2]
    distance_12=numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
    return distance_12

In [79]:
def bond_check(distance):
    """
    Checks a distance to see if it;s a bond.
    """
    if distance >0 and distance<1.5:
        return True
    else:
        return False


In [70]:
xyz_file=numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [71]:
symbols = xyz_file[:,0]
print(symbols)

['O' 'H1' 'H2']


In [72]:
coordinates=xyz_file[:,1:]
print(coordinates)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [73]:
coordinates = coordinates.astype(numpy.float)
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [74]:
num_atoms=len(symbols)
for num1 in range(0, num_atoms):
    for num2 in range(0,num_atoms):
        x_distance=coordinates[num1,0]-coordinates[num2,0]
        y_distance=coordinates[num1,1]-coordinates[num2,1]
        z_distance=coordinates[num1,2]-coordinates[num2,2]
        distance_12=numpy.sqrt(x_distance**2+y_distance**2+x_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]}:{distance_12}')

O to O:0.0
O to H1:0.008642
O to H2:0.9381820000000001
H1 to O:0.008642
H1 to H1:0.0
H1 to H2:0.92954
H2 to O:0.9381820000000001
H2 to H1:0.92954
H2 to H2:0.0


In [75]:
num_atoms=len(symbols)
for num1 in range(0, num_atoms):
    for num2 in range(0,num_atoms):
        if num1>num2:
            x_distance=coordinates[num1,0]-coordinates[num2,0]
            y_distance=coordinates[num1,1]-coordinates[num2,1]
            z_distance=coordinates[num1,2]-coordinates[num2,2]
            distance_12=numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if distance_12<1.5:
                print(F'{symbols[num1]} to {symbols[num2]}:{distance_12:.3f}')

H1 to O:0.969
H2 to O:0.969


In [87]:
num_atoms=len(symbols)
for num1 in range(0, num_atoms):
    for num2 in range(0,num_atoms):
        if num1>num2:
            distance_12=calculate_distance(coordinates[num1], coordinates[num2])
            if bond_check(distance_12) is True:
                print(F'{symbols[num1]} to {symbols[num2]}:{distance_12:.3f}')

H1 to O:0.969
H2 to O:0.969
